# Configuration file for dataset cora

# model
hidden_features: 32

# training
train_lr: 0.001
train_max_epoch: 500
train_patience: 10

# checkpoint available
model_parameter_path:

# optimization
optimize_lr: 0.005
optimize_max_epoch: 1000000
optimize_tolerance: 1

