# Configuration file for dataset ppi

# load data
batch_size: 2

# model
hidden_features: 256

# training
train_lr: 0.005
train_max_epoch: 500
train_patience: 10

# checkpoint available
model_parameter_path:

# optimization
graph_optimization:
  optimize_lr: 0.005
  optimize_max_epoch: 1000000
  optimize_tolerance: 0.001

node_optimization:
  optimize_lr: 0.005
  optimize_max_epoch: 10000
  optimize_tolerance: 0.1

# newton's method
newton_method:
  max_epoch: 500
  tolerance: 0.001

# Broyden's method
broyden_method:
  max_epoch: 500
  tolerance: 0.001