# Configuration file for dataset ppi

# load data
batch_size: 2

# model
hidden_features: 256

# training
train_lr: 0.005
train_max_epoch: 2
train_patience: 10

# checkpoint available
model_parameter_path:

# optimization
optimize_lr: 0.005
optimize_max_epoch: 5
optimize_tolerance: 1