# Configuration file for dataset reddit

# model
hidden_features: 72

# training
train_lr: 0.001
train_max_epoch: 500
train_patience: 10

# checkpoint available
model_parameter_path:

# optimization
graph_optimization:
  optimize_lr: 0.005
  optimize_max_epoch: 1000000
  optimize_tolerance: 1

node_optimization:
  optimize_lr: 0.005
  optimize_max_epoch: 100000
  optimize_tolerance: 0.1