# Configuration file for dataset tu

# load data
dataset_name: 'AIDS'
train_ratio: 0.7
validate_ratio: 0.2
batch_size: 20

# model
hidden_features: 64

# training
train_lr: 0.001
train_max_epoch: 2
train_patience: 10
clip: 2.0

# checkpoint available
model_parameter_path:

# optimization
graph_optimization:
  optimize_lr: 0.005
  optimize_max_epoch: 1000000
  optimize_tolerance: 1

node_optimization:
  optimize_lr: 0.005
  optimize_max_epoch: 100000
  optimize_tolerance: 0.1