# Configuration file for dataset TU:ENZYMES

# load data
dataset_name: 'ENZYMES'
train_ratio: 0.7
validate_ratio: 0.2
batch_size: 20

# model
hidden_features: 16

# training
train_lr: 0.001
train_max_epoch: 500
train_patience: 10
clip: 2.0

# checkpoint available
model_parameter_path:

# optimization
graph_optimization:
  optimize_lr: 0.01
  optimize_max_epoch: 100000
  optimize_tolerance: 0.001

node_optimization:
  optimize_lr: 0.005
  optimize_max_epoch: 10000
  optimize_tolerance: 0.1

# newton's method
newton_method:
  max_epoch: 500
  tolerance: 0.001

# Broyden's method
broyden_method:
  max_epoch: 500
  tolerance: 0.001